# Generated by Django 5.2.1 on 2025-05-30 20:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
        ('tienda', '0003_alter_tarotproduct_link_compra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(default=uuid.uuid4, max_length=50, unique=True, verbose_name='Código de Orden')),
                ('paypal_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Orden PayPal')),
                ('paypal_payment_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID de Pago PayPal')),
                ('estado', models.CharField(choices=[('creada', 'Creada'), ('pendiente', 'Pendiente de Pago'), ('aprobada', 'Aprobada por PayPal'), ('pagada', 'Pago Completado'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada'), ('error', 'Error en Pago')], default='creada', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total a Pagar')),
                ('moneda', models.CharField(default='USD', max_length=3, verbose_name='Moneda')),
                ('email_paypal', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email PayPal del Comprador')),
                ('datos_paypal', models.JSONField(blank=True, default=dict, verbose_name='Datos Completos de PayPal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago Completado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LogWebhookPayPal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('resource_id', models.CharField(blank=True, max_length=100)),
                ('datos_completos', models.JSONField(default=dict)),
                ('procesado', models.BooleanField(default=False)),
                ('error_mensaje', models.TextField(blank=True)),
                ('fecha_recibido', models.DateTimeField(auto_now_add=True)),
                ('orden_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.ordencompra')),
            ],
            options={
                'verbose_name': 'Log Webhook PayPal',
                'verbose_name_plural': 'Logs Webhooks PayPal',
                'ordering': ['-fecha_recibido'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tarotproduct')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finanzas.ordencompra')),
            ],
            options={
                'verbose_name': 'Item de Orden',
                'verbose_name_plural': 'Items de Orden',
                'unique_together': {('orden', 'producto')},
            },
        ),
    ]
