# Generated by Django 5.2.1 on 2025-05-29 23:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_pagado', models.DecimalField(decimal_places=2, help_text='Precio que efectivamente pagó el usuario', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Pagado')),
                ('metodo_pago', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('mercadopago', 'MercadoPago'), ('transferencia', 'Transferencia'), ('manual', 'Asignación Manual'), ('otro', 'Otro')], default='manual', max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='completada', max_length=15, verbose_name='Estado de la Compra')),
                ('referencia_pago', models.CharField(blank=True, help_text='ID de transacción, número de referencia, etc.', max_length=200, verbose_name='Referencia de Pago')),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas para el equipo', verbose_name='Notas del Administrador')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='tienda.tarotproduct', verbose_name='Producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Compra de Producto',
                'verbose_name_plural': 'Compras de Productos',
                'ordering': ['-fecha_compra'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'producto'), name='unique_usuario_producto')],
            },
        ),
    ]
