# Generated by Django 5.2.1 on 2025-05-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_compraproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarotproduct',
            name='link_compra',
            field=models.URLField(blank=True, help_text='URL donde se procesa el pago del producto', max_length=500, null=True, verbose_name='Link de Compra'),
        ),
    ]
