# Generated by Django 5.2.1 on 2025-05-26 04:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Set')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('codigo', models.CharField(help_text='Código único para identificar el set', max_length=20, unique=True, verbose_name='Código único')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Set de Cartas',
                'verbose_name_plural': 'Sets de Cartas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Mazo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('codigo', models.CharField(help_text='Código único para identificar el mazo', max_length=20, unique=True, verbose_name='Código único')),
                ('imagen_reverso', models.ImageField(help_text='Imagen que se muestra en el reverso de todas las cartas de este mazo', upload_to='mazos/reversos/', verbose_name='Imagen del Reverso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mazos', to='oraculo.set', verbose_name='Set al que pertenece')),
            ],
            options={
                'verbose_name': 'Mazo',
                'verbose_name_plural': 'Mazos',
                'ordering': ['set', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número de orden de la carta en el mazo', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Carta')),
                ('imagen', models.ImageField(upload_to='cartas/', verbose_name='Imagen de la Carta')),
                ('significado_normal', models.TextField(help_text='Significado cuando la carta aparece en posición normal', verbose_name='Significado Normal')),
                ('significado_invertido', models.TextField(help_text='Significado cuando la carta aparece invertida', verbose_name='Significado Invertido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas', to='oraculo.mazo', verbose_name='Mazo al que pertenece')),
            ],
            options={
                'verbose_name': 'Carta',
                'verbose_name_plural': 'Cartas',
                'ordering': ['mazo', 'numero'],
                'unique_together': {('numero', 'mazo')},
            },
        ),
    ]
