# Generated by Django 5.2.1 on 2025-05-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='significado_invertido',
            field=models.TextField(blank=True, help_text='Significado cuando la carta aparece invertida', null=True, verbose_name='Significado Invertido'),
        ),
    ]
