# Generated by Django 5.2.1 on 2025-05-28 16:09

import oraculo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0002_alter_carta_significado_invertido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='imagen',
            field=models.ImageField(upload_to=oraculo.models.upload_to_cartas, verbose_name='Imagen de la Carta'),
        ),
        migrations.AlterField(
            model_name='carta',
            name='significado_invertido',
            field=models.TextField(blank=True, help_text='Significado cuando la carta aparece invertida (opcional)', null=True, verbose_name='Significado Invertido'),
        ),
        migrations.AlterField(
            model_name='mazo',
            name='imagen_reverso',
            field=models.ImageField(help_text='Imagen que se muestra en el reverso de todas las cartas de este mazo', upload_to=oraculo.models.upload_to_mazos_reversos, verbose_name='Imagen del Reverso'),
        ),
    ]
