# Generated by Django 5.2.1 on 2025-05-29 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0003_alter_carta_imagen_alter_carta_significado_invertido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={},
        ),
        migrations.RemoveField(
            model_name='set',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='set',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='set',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='set',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='set',
            name='nombre',
        ),
    ]
