# Generated by Django 5.2.1 on 2025-05-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0004_alter_set_options_remove_set_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['nombre'], 'verbose_name': 'Set de Cartas', 'verbose_name_plural': 'Sets de Cartas'},
        ),
        migrations.AddField(
            model_name='set',
            name='codigo',
            field=models.CharField(help_text='Código único para identificar el set', max_length=20, null=True, unique=True, verbose_name='Código único'),
        ),
        migrations.AddField(
            model_name='set',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='set',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Set'),
        ),
    ]
