# Generated by Django 5.2.1 on 2025-05-29 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0006_alter_set_codigo_alter_set_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='codigo',
            field=models.CharField(help_text='Código único para identificar el set', max_length=20, null=True, unique=True, verbose_name='Código único'),
        ),
    ]
