# oraculo/migrations/0009_complementosmazo.py

# Generated by Django 5.2.1 on 2025-05-29 XX:XX

from django.db import migrations, models
import django.db.models.deletion
import oraculo.models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0008_alter_set_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplementosMazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructivo', models.FileField(blank=True, help_text='Archivo con las instrucciones de uso del mazo (PDF, DOC, etc.)', null=True, upload_to=oraculo.models.upload_to_complementos_instructivos, verbose_name='Instructivo')),
                ('plantilla_impresion', models.FileField(blank=True, help_text='Archivo con plantilla para imprimir el mazo (PDF, AI, PSD, etc.)', null=True, upload_to=oraculo.models.upload_to_complementos_plantillas, verbose_name='Plantilla de Impresión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mazo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complementos', to='oraculo.mazo', verbose_name='Mazo')),
            ],
            options={
                'verbose_name': 'Complementos de Mazo',
                'verbose_name_plural': 'Complementos de Mazos',
            },
        ),
    ]