# Generated by Django 5.2.1 on 2025-05-31 04:39

import django.db.models.deletion
import oraculo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oraculo', '0009_complementosmazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la tirada (ej: Tirada del Tiempo)', max_length=100, verbose_name='Nombre de la Tirada')),
                ('imagen_mesa', models.ImageField(help_text='Imagen que muestra las posiciones de las cartas en la mesa', upload_to=oraculo.models.upload_to_tiradas, verbose_name='Imagen de la Mesa')),
                ('posiciones', models.JSONField(default=dict, help_text='Configuración JSON con las posiciones y sus significados', verbose_name='Posiciones de las Cartas')),
                ('permite_invertidas', models.BooleanField(default=True, help_text='Si está activado, algunas cartas podrán aparecer invertidas aleatoriamente', verbose_name='Permite Cartas Invertidas')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción general de la tirada y su propósito', verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, help_text='Si la tirada está disponible para usar', verbose_name='Tirada Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('mazo', models.ForeignKey(help_text='Mazo del cual se tomarán las cartas para esta tirada', on_delete=django.db.models.deletion.CASCADE, related_name='tiradas', to='oraculo.mazo', verbose_name='Mazo asociado')),
            ],
            options={
                'verbose_name': 'Tirada',
                'verbose_name_plural': 'Tiradas',
                'ordering': ['nombre'],
            },
        ),
    ]
